using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace NestedObjects
{
    /// <summary>
    /// Represents a individual student.
    /// </summary>
    public class Student
    {
        /// <summary>
        /// The first and last name of the student.
        /// ex. John Doe
        /// </summary>
        public string FullName { get; set; }

        /// <summary>
        /// The day the student was born. Time is ignored.
        /// </summary>
        public DateTime? DateOfBirth { get; set; }

        /// <summary>
        /// The unique identifier representing the student. 
        /// This number is generated by the database.
        /// </summary>
        public int StudentID { get; set; }
    }
}
